// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zaeniudrsyheulxmibfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZW5pdWRyc3loZXVseG1pYmZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODgzNTQsImV4cCI6MjA2MTQ2NDM1NH0._gXDvG5Lu60XbrPTUK-ZQ-PQp30S3qijkyWYjRAuUm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
